/* Données du quiz Dolphinarium — 6 thématiques x 5 questions (mixte QCM / Vrai-Faux).
 * Format : { theme, type: 'qcm' | 'vf', question, choices (qcm uniquement), answer (index qcm | booléen vf), explication }
 * Fichier JS (et non JSON) : fetch() d'un JSON local échoue en file://, ce module reste importable partout. */
const QUIZ_DATA = [
    // ---------- 1. Espèces & diversité ----------
    { theme: 'Espèces & diversité', type: 'qcm', question: "Quel est le nom scientifique du grand dauphin ?",
        choices: ['Tursiops truncatus', 'Delphinus delphis', 'Orcinus orca', 'Grampus griseus'], answer: 0,
        explication: "Le grand dauphin est Tursiops truncatus, l'espèce la plus étudiée et la plus répandue dans les delphinariums." },
    { theme: 'Espèces & diversité', type: 'vf', question: "L'orque est le plus grand membre de la famille des dauphins (delphinidés).", answer: true,
        explication: "Vrai : l'orque (Orcinus orca) appartient bien aux delphinidés. Ce n'est pas une baleine malgré son surnom d'« épaulard »." },
    { theme: 'Espèces & diversité', type: 'qcm', question: "Quel dauphin vit en eau douce, dans le bassin amazonien ?",
        choices: ["Le dauphin rose de l'Amazone", 'Le dauphin bleu et blanc', 'Le dauphin de Risso', 'Le marsouin commun'], answer: 0,
        explication: "Le boto (Inia geoffrensis), ou dauphin rose de l'Amazone, vit en eau douce. Tous les dauphins ne sont pas marins." },
    { theme: 'Espèces & diversité', type: 'vf', question: "Le dauphin de Risso naît gris et blanchit avec les cicatrices accumulées au fil de sa vie.", answer: true,
        explication: "Vrai : les nombreuses cicatrices (jeux sociaux, calmars, congénères) recouvrent son corps et le rendent presque blanc avec l'âge." },
    { theme: 'Espèces & diversité', type: 'qcm', question: "Comment appelle-t-on un groupe de dauphins ?",
        choices: ['Un pod', 'Un banc', 'Une meute', 'Un essaim'], answer: 0,
        explication: "On parle de « pod » : un groupe social pouvant aller de quelques individus à plusieurs centaines selon l'espèce." },
    // ---------- 2. Anatomie & super-sens ----------
    { theme: 'Anatomie & super-sens', type: 'qcm', question: "Quel organe focalise les clics d'écholocation du dauphin ?",
        choices: ['Le melon', "L'évent", 'Le rostre', 'La nageoire dorsale'], answer: 0,
        explication: "Le melon, masse graisseuse du front, joue le rôle de lentille acoustique pour diriger les clics émis." },
    { theme: 'Anatomie & super-sens', type: 'vf', question: "Les dauphins perçoivent les échos principalement par leur mâchoire inférieure.", answer: true,
        explication: "Vrai : la mâchoire inférieure, remplie de graisse acoustique, conduit les vibrations jusqu'à l'oreille interne." },
    { theme: 'Anatomie & super-sens', type: 'qcm', question: "Combien de temps un grand dauphin peut-il rester en apnée (ordre de grandeur) ?",
        choices: ['~10 minutes', '~1 heure', '~30 secondes', '~2 heures'], answer: 0,
        explication: "Environ 8 à 10 minutes en plongée active. Loin des cachalots, mais suffisant pour chasser en profondeur." },
    { theme: 'Anatomie & super-sens', type: 'vf', question: "Le dauphin respire par réflexe, même endormi.", answer: false,
        explication: "Faux : la respiration est volontaire. C'est pourquoi le dauphin dort d'un seul hémisphère cérébral à la fois pour continuer à respirer." },
    { theme: 'Anatomie & super-sens', type: 'qcm', question: "La nageoire caudale du dauphin bat…",
        choices: ['Verticalement', 'Horizontalement', 'En rotation', 'Elle est fixe, c\'est le corps qui ondule seul'], answer: 0,
        explication: "Les cétacés ondulent verticalement (héritage terrestre), contrairement aux poissons qui ondulent latéralement." },
    // ---------- 3. Communication & intelligence ----------
    { theme: 'Communication & intelligence', type: 'qcm', question: "Qu'est-ce que le « sifflement signature » ?",
        choices: ['Un signal unique propre à chaque individu', 'Un cri d\u2019alarme collectif', 'Le chant des mâles en rut', 'Le bruit du sonar'], answer: 0,
        explication: "Chaque dauphin développe un sifflement signature qui fonctionne comme un prénom pour se reconnaître." },
    { theme: 'Communication & intelligence', type: 'vf', question: "Les dauphins se reconnaissent dans un miroir.", answer: true,
        explication: "Vrai : ils réussissent le test du miroir, signe de conscience de soi partagé avec très peu d'espèces." },
    { theme: 'Communication & intelligence', type: 'qcm', question: "Quel usage d'outil est documenté chez les dauphins sauvages ?",
        choices: ['Des éponges sur le rostre pour fouiller le sable', 'Des bâtons pour pêcher', 'Des coquilles comme armes', 'Des algues comme filets'], answer: 0,
        explication: "À Shark Bay (Australie), les dauphins portent des éponges sur le rostre pour protéger leur nez en fouillant le fond." },
    { theme: 'Communication & intelligence', type: 'vf', question: "Chaque pod possède un dialecte vocal propre.", answer: true,
        explication: "Vrai : les groupes développent des variantes vocales stables, transmises socialement comme un dialecte." },
    { theme: 'Communication & intelligence', type: 'qcm', question: "Les vocalisations des dauphins servent surtout à…",
        choices: ['Coordonner la chasse, les liens sociaux et se repérer', 'Chanter pour séduire uniquement', 'Effrayer les requins', 'Rien, ce sont des bruits aléatoires'], answer: 0,
        explication: "Sifflements (communication) et clics (écholocation) : un double système au service du groupe et de l'orientation." },
    // ---------- 4. Vie sociale & comportement ----------
    { theme: 'Vie sociale & comportement', type: 'qcm', question: "Pourquoi les dauphins « surfent »-ils devant les étraves des bateaux ?",
        choices: ["Ils profitent de la vague d'étrave pour économiser leur énergie", 'Ils attaquent le bateau', 'Ils fuient un prédateur', 'Ils jouent sans aucune raison'], answer: 0,
        explication: "Le « bow-riding » permet de se laisser porter par la vague d'étrave : déplacement à moindre coût énergétique." },
    { theme: 'Vie sociale & comportement', type: 'vf', question: "Les dauphins dorment d'un seul hémisphère cérébral à la fois.", answer: true,
        explication: "Vrai : le sommeil unihémisphérique permet de continuer à respirer volontairement et à surveiller les prédateurs." },
    { theme: 'Vie sociale & comportement', type: 'qcm', question: "Quelle technique de chasse collective est célèbre chez les dauphins ?",
        choices: ['Rabattre les poissons en boule (« bait ball »)', 'Creuser des pièges dans le sable', "Cracher de l'eau comme les poissons-archers", 'Chasser toujours en solitaire'], answer: 0,
        explication: "En équipe, les dauphins encerclent les bancs et les compactent en boule pour les capturer à tour de rôle." },
    { theme: 'Vie sociale & comportement', type: 'vf', question: "Les dauphins peuvent se montrer agressifs, entre eux comme envers d'autres espèces.", answer: true,
        explication: "Vrai : derrière l'image d'Épinal, ce sont des prédateurs capables d'agressivité territoriale et sociale." },
    { theme: 'Vie sociale & comportement', type: 'qcm', question: "Le jeu (surf, bulles, objets) chez le dauphin sert à…",
        choices: ["L'apprentissage et au lien social", 'Rien, pur gaspillage d\u2019énergie', 'Uniquement à séduire', 'Uniquement à chasser'], answer: 0,
        explication: "Le jeu entraîne les jeunes (chasse, coordination) et soude le groupe : c'est un comportement adaptatif." },
    // ---------- 5. Reproduction & cycle de vie ----------
    { theme: 'Reproduction & cycle de vie', type: 'qcm', question: "Quelle est la durée de gestation d'un grand dauphin ?",
        choices: ['~12 mois', '~3 mois', '~6 mois', '~22 mois'], answer: 0,
        explication: "Environ 12 mois, comme chez l'humain… mais pour un seul petit déjà capable de nager à la naissance." },
    { theme: 'Reproduction & cycle de vie', type: 'vf', question: "La femelle met bas d'un seul petit à la fois.", answer: true,
        explication: "Vrai : les jumeaux sont exceptionnels. Toute l'énergie parentale se concentre sur un seul petit." },
    { theme: 'Reproduction & cycle de vie', type: 'qcm', question: "Le petit dauphin naît…",
        choices: ['La queue la première', 'La tête la première', 'Indifféremment', 'Dans un œuf'], answer: 0,
        explication: "La queue sort en premier pour éviter la noyade : le petit prend sa première respiration dès sa sortie." },
    { theme: 'Reproduction & cycle de vie', type: 'vf', question: "L'allaitement du petit peut durer plus d'un an.", answer: true,
        explication: "Vrai : 12 à 18 mois d'allaitement, avec un lait très gras pour une croissance rapide." },
    { theme: 'Reproduction & cycle de vie', type: 'qcm', question: "Quelle est l'espérance de vie d'un grand dauphin en milieu naturel ?",
        choices: ['40 à 50 ans', '~10 ans', '~15 ans', '~100 ans'], answer: 0,
        explication: "40 à 50 ans en moyenne, parfois davantage pour les femelles : une vie longue et sociale." },
    // ---------- 6. Conservation, menaces & idées reçues ----------
    { theme: 'Conservation & idées reçues', type: 'qcm', question: "Quelle est la première cause de mortalité des dauphins sauvages ?",
        choices: ['Les captures accidentelles dans les filets de pêche', 'Les requins', 'Le froid', 'Le manque de jeu'], answer: 0,
        explication: "Les prises accessoires (« bycatch ») tuent des centaines de milliers de cétacés chaque année." },
    { theme: 'Conservation & idées reçues', type: 'vf', question: "Le « sourire » du dauphin prouve qu'il est heureux.", answer: false,
        explication: "Faux : c'est la forme anatomique de sa mâchoire, présente qu'il soit en forme, stressé ou malade." },
    { theme: 'Conservation & idées reçues', type: 'qcm', question: "La chasse au rabattage de Taiji (Japon) vise surtout…",
        choices: ['Des petits cétacés, dont des dauphins', 'Des thons', 'Des requins', 'Des baleines bleues'], answer: 0,
        explication: "La baie de Taiji est tristement célèbre pour ses battues annuelles de dauphins et petits cétacés." },
    { theme: 'Conservation & idées reçues', type: 'vf', question: "Le bruit sous-marin des navires et des sonars perturbe les dauphins.", answer: true,
        explication: "Vrai : la pollution sonore masque leurs clics et sifflements, vitaux pour chasser et communiquer." },
    { theme: 'Conservation & idées reçues', type: 'qcm', question: "Face à un dauphin sauvage, la bonne attitude est…",
        choices: ['Observer à distance, sans toucher ni nourrir', 'Nager vers lui pour le toucher', 'Lui donner du poisson', "L'attraper pour une photo"], answer: 0,
        explication: "Distance, calme et aucun nourrissage : un animal sauvage reste imprévisible et le toucher le stresse."
        }
];
